name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level (optional)'
        required: false
        default: 'info'
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'testing'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cache: 'pip'
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: pytest -s .\testqt.py
